### ISSUE TITLE
AppKit sample

### ISSUE THREAD

**Issue by helje5** [ra1028/DifferenceKit#42]
Hi,

isn't the `dataInput` property superfluous?

Dropping `dataInput` and just adding a `didSet` seems to work fine, but maybe I'm missing something:
```swift
    private var data = (0x1F600...0x1F647).compactMap { UnicodeScalar($0).map(String.init) } {
        didSet {
            let changeset = StagedChangeset(source: oldValue, target: data)
            collectionView.reload(using: changeset) { data in }
            tableView.reload(using: changeset, with: .effectFade) { data in }
        }
    }
```

**Comment by ra1028** [comment]
Hi, @helje5

DifferenceKit calls performBatchUpdates in stages.

It's because that there are some combinations of difference that cause crash when applying to a table view simultaneously.

Therefore, I separated the `dataInput` and the `data` that referenced by the table view.

Please see the Readme or docs for details.

**Comment by helje5** [comment]
OK, thanks.
